name: Arkalender Release
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: ${{ endsWith(github.event.head_commit.message, 'REL') }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_use_lualatex: true
          continue_on_error: true
          args: -interaction=nonstopmode
          root_file: arkalender.tex
          
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: arkalender.pdf
          
      - name: Create Pre-Release
        id: create_pre_release
        if: ${{ endsWith(github.event.head_commit.message, 'PREL') }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create 2025v1.0 --generate-notes --title "Arkalender 2025v1.0 – Entwurf" --prerelease
          
      - name: Create Release
        id: create_release
        if: ${{ !endsWith(github.event.head_commit.message, 'PREL') }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create 2025v1.0 --generate-notes --title "Arkalender 2025v1.0"
          
      - name: Rename Asset File
        id: rename-asset-file
        env:
          GH_TOKEN: ${{ github.token }}
        run:
          mv arkalender.pdf arkalender-2025v1.0.pdf
          
      - name: Upload Arkalender
        id: upload-sop
        env:
          GH_TOKEN: ${{ github.token }}
        run:
          gh release upload 2025v1.0 './arkalender-2025v1.0.pdf'
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}